### ISSUE TITLE
Error on UMLS connection  

### ISSUE THREAD

**Issue by Vortex10** [tmills/ctakes-docker#37]
Hi Tim,

I was trying to configure following the steps on the tutorial, however UMLS replaced the username and password to SSO, is this tutorial still valid?

What should be the configuration for the following file?

https://github.com/tmills/ctakes-docker/blob/master/env_file_sample.txt

Thanks

```

Certificate was added to keystore
>>> Setting defaultBrokerURL to:https://192.168.68.103:61616
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/apache-ctakes-4.0.0/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/apache-uima-as-2.10.3/apache-activemq/lib/slf4j-log4j12-1.7.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
  UMLS Account at https://uts-ws.nlm.nih.gov/restful/isValidUMLSUser is not valid for user <username> with <password>

org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/apache-ctakes-4.0.0/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
	at org.apache.uima.aae.controller.PrimitiveAnalysisEngineController_impl.initializeAnalysisEngine(PrimitiveAnalysisEngineController_impl.java:376)
	at org.apache.uima.aae.UimaAsPriorityBasedThreadFactory$1.run(UimaAsPriorityBasedThreadFactory.java:141)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/apache-ctakes-4.0.0/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:274)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:172)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:435)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:379)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:192)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)

```

**Comment by tmills** [comment]
You're right, the tutorial is probably not valid anymore. I have a new
docker image I use for the SSO change, but it probably won't fit with the
rest of the tutorial.

**Comment by Vortex10** [comment]
Would you have the process to build the file with the SSO or the docker build file? And the new repo

**Comment by tmills** [comment]
Here is the repo:
https://github.com/Machine-Learning-for-Medical-Language/ctakes-covid-container

**Comment by chen-yifu** [comment]
Hi, is this repo still available anywhere? Thank you!

**Comment by tmills** [comment]
Hi @chen-yifu , I've re-created it so the link above should work now.

**Comment by chen-yifu** [comment]
Thank you very much!
